# Generated by Django 3.1.4 on 2020-12-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='desc_hospital',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
